use crate::model::{Report, Severity};
use std::fmt::Write;

pub fn render_json(report: &Report) -> Result<String, String> {
    serde_json::to_string_pretty(report)
        .map(|s| format!("{s}\n"))
        .map_err(|e| e.to_string())
}

pub fn render_markdown(report: &Report) -> String {
    let mut out = String::new();
    writeln!(out, "# Collection migration report\n").unwrap();
    writeln!(out, "**Verdict: {}**\n", verdict_label(&report.verdict)).unwrap();
    writeln!(out, "> Structural comparison only. No requests were sent. Variable values and URL credentials are redacted.\n").unwrap();
    writeln!(out, "## Summary\n").unwrap();
    writeln!(out, "| | Errors | Warnings | Notes |").unwrap();
    writeln!(out, "| --- | ---: | ---: | ---: |").unwrap();
    writeln!(
        out,
        "| Findings | {} | {} | {} |\n",
        report.summary.errors, report.summary.warnings, report.summary.info
    )
    .unwrap();
    writeln!(
        out,
        "| Artifact | Source ({}) | Target ({}) |",
        escape(&report.source_format),
        escape(&report.target_format)
    )
    .unwrap();
    writeln!(out, "| --- | ---: | ---: |").unwrap();
    let s = &report.summary.source;
    let t = &report.summary.target;
    for (name, a, b) in [
        ("Folders", s.folders, t.folders),
        ("Requests", s.requests, t.requests),
        ("Variables", s.variables, t.variables),
        ("Scripts", s.scripts, t.scripts),
        ("Examples", s.examples, t.examples),
        ("Body bytes", s.body_bytes, t.body_bytes),
    ] {
        writeln!(out, "| {name} | {a} | {b} |").unwrap();
    }
    writeln!(out, "\n## Findings\n").unwrap();
    if report.findings.is_empty() {
        writeln!(out, "No structural differences found. Review and run your client-specific smoke tests before switching.\n").unwrap();
    } else {
        writeln!(out, "| Severity | Code | Artifact | Finding | Evidence |").unwrap();
        writeln!(out, "| --- | --- | --- | --- | --- |").unwrap();
        for f in &report.findings {
            writeln!(
                out,
                "| {} | `{}` | `{}` | {} | {} |",
                severity_label(&f.severity),
                escape(&f.code),
                escape(&f.path),
                escape(&f.message),
                escape(&f.evidence)
            )
            .unwrap();
        }
        writeln!(out).unwrap();
    }
    writeln!(out, "## Review checklist\n").unwrap();
    writeln!(
        out,
        "- [ ] Confirm every error is fixed or explicitly accepted."
    )
    .unwrap();
    writeln!(
        out,
        "- [ ] Review inherited auth and client-specific script APIs."
    )
    .unwrap();
    writeln!(
        out,
        "- [ ] Run representative requests in a non-production environment."
    )
    .unwrap();
    writeln!(
        out,
        "- [ ] Commit this report with the migration fixture.\n"
    )
    .unwrap();
    writeln!(
        out,
        "_Generated by Collection Escape Hatch {}._",
        env!("CARGO_PKG_VERSION")
    )
    .unwrap();
    out
}

fn severity_label(s: &Severity) -> &'static str {
    match s {
        Severity::Error => "ERROR",
        Severity::Warning => "WARNING",
        Severity::Info => "INFO",
    }
}
fn verdict_label(v: &str) -> &'static str {
    match v {
        "verified" => "Verified",
        "review-required" => "Review required",
        _ => "Changes detected",
    }
}
fn escape(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::*;
    #[test]
    fn markdown_has_privacy_notice() {
        let report = Report {
            schema: "x".into(),
            verdict: "verified".into(),
            source_format: "a".into(),
            target_format: "b".into(),
            summary: Summary {
                errors: 0,
                warnings: 0,
                info: 0,
                source: Counts::default(),
                target: Counts::default(),
            },
            findings: vec![],
        };
        assert!(render_markdown(&report).contains("Variable values"));
    }
}
